CREATE TABLE IF NOT EXISTS `#__jdm_articles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `jdoc_key` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `manual` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL,
  `heading` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `filename` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `display_title` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL,
  `state` tinyint(4) NOT NULL DEFAULT '0',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` datetime DEFAULT NULL,
  `html` mediumtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `state` (`state`),
  KEY `manual` (`manual`),
  KEY `language` (`language`),
  KEY `heading` (`heading`),
  KEY `filename` (`filename`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__jdm_article_stashes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `page_id` int(11) NOT NULL,
  `jdoc_key` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `manual` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL,
  `heading` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `filename` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `display_title` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL,
  `pr` int(11) NOT NULL DEFAULT '0',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `commit_message` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comments` text COLLATE utf8mb4_unicode_ci,
  `markdown_text` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `page_id` (`page_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__jdm_languages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `index_language` int(11) NOT NULL DEFAULT '0',
  `page_language` int(11) NOT NULL DEFAULT '0',
  `lft` int(11) NOT NULL DEFAULT '0',
  `rgt` int(11) NOT NULL DEFAULT '0',
  `state` tinyint(3) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `#__jdm_languages` (`id`, `code`, `title`, `index_language`, `page_language`, `lft`, `rgt`, `state`) VALUES
(1, 'en', 'English', 1, 1, 0, 0, 1),
(2, 'nl', 'Dutch', 1, 1, 0, 0, 1),
(3, 'fr', 'French', 1, 1, 0, 0, 1),
(4, 'de', 'German', 1, 1, 0, 0, 1),
(5, 'es', 'Spanish', 1, 1, 0, 0, 1),
(6, 'pt', 'Portuguese', 1, 1, 0, 0, 1),
(7, 'pt-br', 'Portuguese-Brazil', 1, 1, 0, 0, 1),
(8, 'ru', 'Russian', 1, 1, 0, 0, 1);

CREATE TABLE IF NOT EXISTS `#__jdm_manuals` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `manual` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `heading_ini` VARCHAR(128) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `filename_ini` VARCHAR(128) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `state` tinyint(3) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `#__jdm_manuals` (`id`, `manual`, `title`, `heading_ini`, `filename_ini`, `state`) VALUES
(1, 'user', 'Joomla 4 User Manual', 'getting-started', 'introduction-to-joomla.md', 1),
(2, 'help', 'Joomla 4 Help Screens', 'help-screens', 'start-here.md', 1),
(3, 'developer', 'Joomla 4 Developer Manual', 'getting-started', 'developer-required-software.md', 1),
(4, 'docs', 'Joomla 4 Documenter Manual', 'jdocmanual', 'introduction-to-jdocmanual.md', 0);

CREATE TABLE IF NOT EXISTS `#__jdm_menus` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `manual` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `language` char(8) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'en',
  `menu` mediumtext COLLATE utf8mb4_unicode_ci,
  `state` tinyint(4) NOT NULL DEFAULT '1',
  `last_update` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS`#__jdm_menu_stashes` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `manual` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `pr` int(11) NOT NULL DEFAULT '0',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `commit_message` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comments` text COLLATE utf8mb4_unicode_ci,
  `menu_text` text COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `#__jdm_menu_stashes`
  ADD PRIMARY KEY (`id`),
  ADD KEY `manual` (`manual`),
  ADD KEY `user_id` (`user_id`);

ALTER TABLE `#__jdm_menu_stashes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

CREATE TABLE IF NOT EXISTS `#__jdm_menu_headings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `manual` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `language` char(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `heading` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `display_title` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=716 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `#__jdm_menu_headings` (`id`, `manual`, `language`, `heading`, `display_title`) VALUES
(1, 'user', 'en', 'getting-started', 'Getting Started'),
(2, 'user', 'en', 'articles', 'Articles'),
(3, 'user', 'en', 'articles-access', 'Articles - Access'),
(4, 'user', 'en', 'articles-metadata', 'Articles - Metadata'),
(5, 'user', 'en', 'banners', 'Banners'),
(6, 'user', 'en', 'command-line-interface', 'Command '),
(7, 'user', 'en', 'configuration', 'Configuration'),
(8, 'user', 'en', 'contacts', 'Contacts'),
(9, 'user', 'en', 'dashboards', 'Dashboards'),
(10, 'user', 'en', 'editors', 'Editors'),
(11, 'user', 'en', 'extensions', 'Extensions'),
(12, 'user', 'en', 'fields', 'Fields'),
(13, 'user', 'en', 'help', 'Help'),
(14, 'user', 'en', 'hosting', 'Hosting'),
(15, 'user', 'en', 'installation-variations', 'Installation Variations'),
(16, 'user', 'en', 'languages', 'Languages'),
(17, 'user', 'en', 'media', 'Media'),
(18, 'user', 'en', 'menus', 'Menus'),
(19, 'user', 'en', 'migration', 'Migration'),
(20, 'user', 'en', 'modules', 'Modules'),
(21, 'user', 'en', 'news-feeds', 'News Feeds'),
(22, 'user', 'en', 'performance', 'Performance'),
(23, 'user', 'en', 'plugins', 'Plugins'),
(24, 'user', 'en', 'privacy', 'Privacy'),
(25, 'user', 'en', 'problems', 'Problems'),
(26, 'user', 'en', 'reference', 'Reference'),
(27, 'user', 'en', 'security', 'Security'),
(28, 'user', 'en', 'seo', 'SEO'),
(29, 'user', 'en', 'smart-search', 'Smart Search'),
(30, 'user', 'en', 'system', 'System'),
(31, 'user', 'en', 'tags', 'Tags'),
(32, 'user', 'en', 'templates', 'Templates'),
(33, 'user', 'en', 'template-tips', 'Template Tips'),
(34, 'user', 'en', 'test-installations', 'Test Installations'),
(35, 'user', 'en', 'users', 'Users'),
(36, 'user', 'en', 'workflows', 'Workflows'),
(37, 'help', 'en', 'admin-modules', 'Admin Modules'),
(38, 'help', 'en', 'articles', 'Articles'),
(39, 'help', 'en', 'banners', 'Banners'),
(40, 'help', 'en', 'cache', 'Cache'),
(41, 'help', 'en', 'chunks', 'Chunks'),
(42, 'help', 'en', 'component', 'Component'),
(43, 'help', 'en', 'components', 'Components'),
(44, 'help', 'en', 'contacts', 'Contacts'),
(45, 'help', 'en', 'content-security-policy', 'Contact Security Policy'),
(46, 'help', 'en', 'editors', 'Editors'),
(47, 'help', 'en', 'extensions', 'Extensions'),
(48, 'help', 'en', 'fields', 'Fields'),
(49, 'help', 'en', 'glossary', 'Glossary'),
(50, 'help', 'en', 'help-screens', 'Help Screens'),
(51, 'help', 'en', 'information', 'Infromation'),
(52, 'help', 'en', 'install-or-update', 'Install or Update'),
(53, 'help', 'en', 'languages', 'Languages'),
(54, 'help', 'en', 'mail', 'Mail'),
(55, 'help', 'en', 'media', 'Media'),
(56, 'help', 'en', 'menu-items', 'Menu-items'),
(57, 'help', 'en', 'menus', 'Menus'),
(58, 'help', 'en', 'messages', 'Messages'),
(59, 'help', 'en', 'modules', 'Modules'),
(60, 'help', 'en', 'multilingual-associations', 'Multilingual Associations'),
(61, 'help', 'en', 'my-profile', 'My Profile'),
(62, 'help', 'en', 'news-feed', 'News Feed'),
(63, 'help', 'en', 'permissions', 'Permissions'),
(64, 'help', 'en', 'plugins', 'Plugins'),
(65, 'help', 'en', 'post-install-messages', 'Post-install Messages'),
(66, 'help', 'en', 'privacy', 'Privacy'),
(67, 'help', 'en', 'private-messages', 'Private Messages'),
(68, 'help', 'en', 'redirect', 'Redirect'),
(69, 'help', 'en', 'site', 'Site'),
(70, 'help', 'en', 'site-modules', 'Site Modules'),
(71, 'help', 'en', 'smart-search', 'Smart Search'),
(72, 'help', 'en', 'tags', 'Tags'),
(73, 'help', 'en', 'templates', 'Templates'),
(74, 'help', 'en', 'update-sites', 'Update Sites'),
(75, 'help', 'en', 'users', 'Users'),
(76, 'help', 'en', 'workflow', 'Workflow'),
(77, 'developer', 'en', 'getting-started', 'Getting Started'),
(78, 'developer', 'en', 'developer-information', 'Developer Information'),
(79, 'developer', 'en', 'plugin-development', 'Plugin Development'),
(80, 'developer', 'en', 'module-development', 'Module Development'),
(81, 'developer', 'en', 'developing-an-mvc-component', 'Developing an MVC Component'),
(82, 'developer', 'en', 'mvc-anatomy', 'MVC Anatomy'),
(83, 'developer', 'en', 'mvc-examples', 'MVC Examples'),
(84, 'developer', 'en', 'cli-development', 'CLI Development'),
(85, 'developer', 'en', 'database', 'Database'),
(86, 'developer', 'en', 'coding-examples', 'Coding Examples'),
(87, 'developer', 'en', 'advanced-developer', 'Advanced Developer'),
(88, 'developer', 'en', 'advanced-administrator', 'Advanced Administrator'),
(89, 'developer', 'en', 'unclassified', 'Unclassified'),
(90, 'help', 'de', 'admin-modules', 'Admin-Module'),
(91, 'help', 'de', 'articles', 'Artikel'),
(92, 'help', 'de', 'banners', 'Banner'),
(93, 'help', 'de', 'cache', 'Zwischenspeicher'),
(94, 'help', 'de', 'chunks', 'Brocken'),
(95, 'help', 'de', 'component', 'Komponente'),
(96, 'help', 'de', 'components', 'Komponenten'),
(97, 'help', 'de', 'contacts', 'Kontakte'),
(98, 'help', 'de', 'content-security-policy', 'Wenden Sie sich an die Sicherheitsrichtlinie'),
(99, 'help', 'de', 'editors', 'Redakteure'),
(100, 'help', 'de', 'extensions', 'Erweiterungen'),
(101, 'help', 'de', 'fields', 'Felder'),
(102, 'help', 'de', 'glossary', 'Glossar'),
(103, 'help', 'de', 'help-screens', 'Hilfebildschirme'),
(104, 'help', 'de', 'information', 'Informationen'),
(105, 'help', 'de', 'install-or-update', 'Installieren oder aktualisieren'),
(106, 'help', 'de', 'languages', 'Sprachen'),
(107, 'help', 'de', 'mail', 'Post'),
(108, 'help', 'de', 'media', 'Medien'),
(109, 'help', 'de', 'menu-items', 'Menüpunkte'),
(110, 'help', 'de', 'menus', 'Menüs'),
(111, 'help', 'de', 'messages', 'Mitteilungen'),
(112, 'help', 'de', 'modules', 'Module'),
(113, 'help', 'de', 'multilingual-associations', 'Mehrsprachige Verbände'),
(114, 'help', 'de', 'my-profile', 'Mein Profil'),
(115, 'help', 'de', 'news-feed', 'Neuigkeiten'),
(116, 'help', 'de', 'permissions', 'Berechtigungen'),
(117, 'help', 'de', 'plugins', 'Plugins'),
(118, 'help', 'de', 'post-install-messages', 'Nachrichten nach der Installation'),
(119, 'help', 'de', 'privacy', 'Privatsphäre'),
(120, 'help', 'de', 'private-messages', 'Private Nachrichten'),
(121, 'help', 'de', 'redirect', 'Umleiten'),
(122, 'help', 'de', 'site', 'Grundstück'),
(123, 'help', 'de', 'site-modules', 'Site-Module'),
(124, 'help', 'de', 'smart-search', 'Intelligente Suche'),
(125, 'help', 'de', 'tags', 'Stichworte'),
(126, 'help', 'de', 'templates', 'Vorlagen'),
(127, 'help', 'de', 'update-sites', 'Websites aktualisieren'),
(128, 'help', 'de', 'users', 'Benutzer'),
(129, 'help', 'de', 'workflow', 'Arbeitsablauf'),
(130, 'user', 'de', 'getting-started', 'Einstieg'),
(131, 'user', 'de', 'articles', 'Artikel'),
(132, 'user', 'de', 'articles-access', 'Artikel - Zugang'),
(133, 'user', 'de', 'articles-metadata', 'Artikel - Metadaten'),
(134, 'user', 'de', 'banners', 'Banner'),
(135, 'user', 'de', 'command-line-interface', 'Befehl'),
(136, 'user', 'de', 'configuration', 'Aufbau'),
(137, 'user', 'de', 'contacts', 'Kontakte'),
(138, 'user', 'de', 'dashboards', 'Dashboards'),
(139, 'user', 'de', 'editors', 'Redakteure'),
(140, 'user', 'de', 'extensions', 'Erweiterungen'),
(141, 'user', 'de', 'fields', 'Felder'),
(142, 'user', 'de', 'help', 'Hilfe'),
(143, 'user', 'de', 'hosting', 'Gastgeber'),
(144, 'user', 'de', 'installation-variations', 'Installationsvarianten'),
(145, 'user', 'de', 'languages', 'Sprachen'),
(146, 'user', 'de', 'media', 'Medien'),
(147, 'user', 'de', 'menus', 'Menüs'),
(148, 'user', 'de', 'migration', 'Migration'),
(149, 'user', 'de', 'modules', 'Module'),
(150, 'user', 'de', 'news-feeds', 'News-Feeds'),
(151, 'user', 'de', 'performance', 'Leistung'),
(152, 'user', 'de', 'plugins', 'Plugins'),
(153, 'user', 'de', 'privacy', 'Privatsphäre'),
(154, 'user', 'de', 'problems', 'Probleme'),
(155, 'user', 'de', 'reference', 'Referenz'),
(156, 'user', 'de', 'security', 'Sicherheit'),
(157, 'user', 'de', 'seo', 'SEO'),
(158, 'user', 'de', 'smart-search', 'Intelligente Suche'),
(159, 'user', 'de', 'system', 'System'),
(160, 'user', 'de', 'tags', 'Stichworte'),
(161, 'user', 'de', 'templates', 'Vorlagen'),
(162, 'user', 'de', 'template-tips', 'Vorlagen-Tipps'),
(163, 'user', 'de', 'test-installations', 'Testinstallationen'),
(164, 'user', 'de', 'users', 'Benutzer'),
(165, 'user', 'de', 'workflows', 'Arbeitsabläufe'),
(166, 'developer', 'de', 'getting-started', 'Einstieg'),
(167, 'developer', 'de', 'developer-information', 'Entwicklerinformationen'),
(168, 'developer', 'de', 'plugin-development', 'Plugin-Entwicklung'),
(169, 'developer', 'de', 'module-development', 'Modulentwicklung'),
(170, 'developer', 'de', 'developing-an-mvc-component', 'Entwicklung einer MVC-Komponente'),
(171, 'developer', 'de', 'mvc-anatomy', 'MVC-Anatomie'),
(172, 'developer', 'de', 'mvc-examples', 'MVC-Beispiele'),
(173, 'developer', 'de', 'cli-development', 'CLI-Entwicklung'),
(174, 'developer', 'de', 'database', 'Datenbank'),
(175, 'developer', 'de', 'coding-examples', 'Codierungsbeispiele'),
(176, 'developer', 'de', 'advanced-developer', 'Fortgeschrittener Entwickler'),
(177, 'developer', 'de', 'advanced-administrator', 'Erweiterter Administrator'),
(178, 'developer', 'de', 'unclassified', 'Nicht klassifiziert'),
(179, 'help', 'fr', 'admin-modules', 'Modules d\'administration'),
(180, 'help', 'fr', 'articles', 'Des articles'),
(181, 'help', 'fr', 'banners', 'Bannières'),
(182, 'help', 'fr', 'cache', 'Cache'),
(183, 'help', 'fr', 'chunks', 'Morceaux'),
(184, 'help', 'fr', 'component', 'Composant'),
(185, 'help', 'fr', 'components', 'Composants'),
(186, 'help', 'fr', 'contacts', 'Contacts'),
(187, 'help', 'fr', 'content-security-policy', 'Contacter la politique de sécurité'),
(188, 'help', 'fr', 'editors', 'Éditeurs'),
(189, 'help', 'fr', 'extensions', 'Rallonges'),
(190, 'help', 'fr', 'fields', 'Des champs'),
(191, 'help', 'fr', 'glossary', 'Glossaire'),
(192, 'help', 'fr', 'help-screens', 'Écrans d\'aide'),
(193, 'help', 'fr', 'information', 'Informations'),
(194, 'help', 'fr', 'install-or-update', 'Installer ou mettre à jour'),
(195, 'help', 'fr', 'languages', 'Langues'),
(196, 'help', 'fr', 'mail', 'Poster'),
(197, 'help', 'fr', 'media', 'médias'),
(198, 'help', 'fr', 'menu-items', 'éléments de menu'),
(199, 'help', 'fr', 'menus', 'Menus'),
(200, 'help', 'fr', 'messages', 'messages'),
(201, 'help', 'fr', 'modules', 'Modules'),
(202, 'help', 'fr', 'multilingual-associations', 'Associations multilingues'),
(203, 'help', 'fr', 'my-profile', 'Mon profil'),
(204, 'help', 'fr', 'news-feed', 'Fil d\'actualité'),
(205, 'help', 'fr', 'permissions', 'Autorisations'),
(206, 'help', 'fr', 'plugins', 'Plugins'),
(207, 'help', 'fr', 'post-install-messages', 'Messages post-installation'),
(208, 'help', 'fr', 'privacy', 'Confidentialité'),
(209, 'help', 'fr', 'private-messages', 'Messages privés'),
(210, 'help', 'fr', 'redirect', 'Réorienter'),
(211, 'help', 'fr', 'site', 'Placer'),
(212, 'help', 'fr', 'site-modules', 'Modules de site'),
(213, 'help', 'fr', 'smart-search', 'Recherche intelligente'),
(214, 'help', 'fr', 'tags', 'Mots clés'),
(215, 'help', 'fr', 'templates', 'Modèles'),
(216, 'help', 'fr', 'update-sites', 'Mettre à jour les sites'),
(217, 'help', 'fr', 'users', 'Utilisateurs'),
(218, 'help', 'fr', 'workflow', 'Flux de travail'),
(219, 'user', 'fr', 'getting-started', 'Commencer'),
(220, 'user', 'fr', 'articles', 'Des articles'),
(221, 'user', 'fr', 'articles-access', 'Articles - Accès'),
(222, 'user', 'fr', 'articles-metadata', 'Articles - Métadonnées'),
(223, 'user', 'fr', 'banners', 'Bannières'),
(224, 'user', 'fr', 'command-line-interface', 'Commande'),
(225, 'user', 'fr', 'configuration', 'Configuration'),
(226, 'user', 'fr', 'contacts', 'Contacts'),
(227, 'user', 'fr', 'dashboards', 'Tableaux de bord'),
(228, 'user', 'fr', 'editors', 'Éditeurs'),
(229, 'user', 'fr', 'extensions', 'Rallonges'),
(230, 'user', 'fr', 'fields', 'Des champs'),
(231, 'user', 'fr', 'help', 'Aider'),
(232, 'user', 'fr', 'hosting', 'Hébergement'),
(233, 'user', 'fr', 'installation-variations', 'Variantes d\'installation'),
(234, 'user', 'fr', 'languages', 'Langues'),
(235, 'user', 'fr', 'media', 'Médias'),
(236, 'user', 'fr', 'menus', 'Menus'),
(237, 'user', 'fr', 'migration', 'Migration'),
(238, 'user', 'fr', 'modules', 'Modules'),
(239, 'user', 'fr', 'news-feeds', 'Fil d\'actualité'),
(240, 'user', 'fr', 'performance', 'Performance'),
(241, 'user', 'fr', 'plugins', 'Plugins'),
(242, 'user', 'fr', 'privacy', 'Confidentialité'),
(243, 'user', 'fr', 'problems', 'Problèmes'),
(244, 'user', 'fr', 'reference', 'Référence'),
(245, 'user', 'fr', 'security', 'Sécurité'),
(246, 'user', 'fr', 'seo', 'référencement'),
(247, 'user', 'fr', 'smart-search', 'Recherche intelligente'),
(248, 'user', 'fr', 'system', 'Système'),
(249, 'user', 'fr', 'tags', 'Mots clés'),
(250, 'user', 'fr', 'templates', 'Modèles'),
(251, 'user', 'fr', 'template-tips', 'Conseils sur les modèles'),
(252, 'user', 'fr', 'test-installations', 'Installations d\'essai'),
(253, 'user', 'fr', 'users', 'Utilisateurs'),
(254, 'user', 'fr', 'workflows', 'Flux de travail'),
(255, 'developer', 'fr', 'getting-started', 'Commencer'),
(256, 'developer', 'fr', 'developer-information', 'Informations pour les développeurs'),
(257, 'developer', 'fr', 'plugin-development', 'Développement de plugins'),
(258, 'developer', 'fr', 'module-development', 'Développement de modules'),
(259, 'developer', 'fr', 'developing-an-mvc-component', 'Développement d\'un composant MVC'),
(260, 'developer', 'fr', 'mvc-anatomy', 'Anatomie MVC'),
(261, 'developer', 'fr', 'mvc-examples', 'Exemples MVC'),
(262, 'developer', 'fr', 'cli-development', 'Développement CLI'),
(263, 'developer', 'fr', 'database', 'Base de données'),
(264, 'developer', 'fr', 'coding-examples', 'Exemples de codage'),
(265, 'developer', 'fr', 'advanced-developer', 'Développeur avancé'),
(266, 'developer', 'fr', 'advanced-administrator', 'Administrateur avancé'),
(267, 'developer', 'fr', 'unclassified', 'Non classé'),
(268, 'help', 'es', 'admin-modules', 'Módulos de administración'),
(269, 'help', 'es', 'articles', 'Artículos'),
(270, 'help', 'es', 'banners', 'pancartas'),
(271, 'help', 'es', 'cache', 'Cache'),
(272, 'help', 'es', 'chunks', 'Trozos'),
(273, 'help', 'es', 'component', 'Componente'),
(274, 'help', 'es', 'components', 'Componentes'),
(275, 'help', 'es', 'contacts', 'Contactos'),
(276, 'help', 'es', 'content-security-policy', 'Política de seguridad de contacto'),
(277, 'help', 'es', 'editors', 'Editores'),
(278, 'help', 'es', 'extensions', 'Extensiones'),
(279, 'help', 'es', 'fields', 'Campos'),
(280, 'help', 'es', 'glossary', 'Glosario'),
(281, 'help', 'es', 'help-screens', 'Pantallas de ayuda'),
(282, 'help', 'es', 'information', 'Información'),
(283, 'help', 'es', 'install-or-update', 'Instalar o Actualizar'),
(284, 'help', 'es', 'languages', 'Idiomas'),
(285, 'help', 'es', 'mail', 'Correo'),
(286, 'help', 'es', 'media', 'medios de comunicación'),
(287, 'help', 'es', 'menu-items', 'elementos de menú'),
(288, 'help', 'es', 'menus', 'Menús'),
(289, 'help', 'es', 'messages', 'Mensajes'),
(290, 'help', 'es', 'modules', 'Módulos'),
(291, 'help', 'es', 'multilingual-associations', 'Asociaciones Multilingües'),
(292, 'help', 'es', 'my-profile', 'Mi perfil'),
(293, 'help', 'es', 'news-feed', 'Noticias'),
(294, 'help', 'es', 'permissions', 'permisos'),
(295, 'help', 'es', 'plugins', 'Complementos'),
(296, 'help', 'es', 'post-install-messages', 'Mensajes posteriores a la instalación'),
(297, 'help', 'es', 'privacy', 'Privacidad'),
(298, 'help', 'es', 'private-messages', 'mensajes privados'),
(299, 'help', 'es', 'redirect', 'redirigir'),
(300, 'help', 'es', 'site', 'Sitio'),
(301, 'help', 'es', 'site-modules', 'Módulos del sitio'),
(302, 'help', 'es', 'smart-search', 'Busqueda inteligente'),
(303, 'help', 'es', 'tags', 'Etiquetas'),
(304, 'help', 'es', 'templates', 'Plantillas'),
(305, 'help', 'es', 'update-sites', 'Actualizar sitios'),
(306, 'help', 'es', 'users', 'Usuarios'),
(307, 'help', 'es', 'workflow', 'flujo de trabajo'),
(308, 'user', 'es', 'getting-started', 'Empezando'),
(309, 'user', 'es', 'articles', 'Artículos'),
(310, 'user', 'es', 'articles-access', 'Artículos - Acceso'),
(311, 'user', 'es', 'articles-metadata', 'Artículos - Metadatos'),
(312, 'user', 'es', 'banners', 'pancartas'),
(313, 'user', 'es', 'command-line-interface', 'Dominio'),
(314, 'user', 'es', 'configuration', 'Configuración'),
(315, 'user', 'es', 'contacts', 'Contactos'),
(316, 'user', 'es', 'dashboards', 'Tableros'),
(317, 'user', 'es', 'editors', 'Editores'),
(318, 'user', 'es', 'extensions', 'Extensiones'),
(319, 'user', 'es', 'fields', 'Campos'),
(320, 'user', 'es', 'help', 'Ayuda'),
(321, 'user', 'es', 'hosting', 'Alojamiento'),
(322, 'user', 'es', 'installation-variations', 'Variaciones de instalación'),
(323, 'user', 'es', 'languages', 'Idiomas'),
(324, 'user', 'es', 'media', 'Medios de comunicación'),
(325, 'user', 'es', 'menus', 'Menús'),
(326, 'user', 'es', 'migration', 'Migración'),
(327, 'user', 'es', 'modules', 'Módulos'),
(328, 'user', 'es', 'news-feeds', 'Noticiero'),
(329, 'user', 'es', 'performance', 'Actuación'),
(330, 'user', 'es', 'plugins', 'Complementos'),
(331, 'user', 'es', 'privacy', 'Privacidad'),
(332, 'user', 'es', 'problems', 'Problemas'),
(333, 'user', 'es', 'reference', 'Referencia'),
(334, 'user', 'es', 'security', 'Seguridad'),
(335, 'user', 'es', 'seo', 'SEO'),
(336, 'user', 'es', 'smart-search', 'Busqueda inteligente'),
(337, 'user', 'es', 'system', 'Sistema'),
(338, 'user', 'es', 'tags', 'Etiquetas'),
(339, 'user', 'es', 'templates', 'Plantillas'),
(340, 'user', 'es', 'template-tips', 'Consejos de plantilla'),
(341, 'user', 'es', 'test-installations', 'Instalaciones de prueba'),
(342, 'user', 'es', 'users', 'Usuarios'),
(343, 'user', 'es', 'workflows', 'Flujos de trabajo'),
(344, 'developer', 'es', 'getting-started', 'Empezando'),
(345, 'developer', 'es', 'developer-information', 'Información del desarrollador'),
(346, 'developer', 'es', 'plugin-development', 'Desarrollo de complementos'),
(347, 'developer', 'es', 'module-development', 'Desarrollo de módulos'),
(348, 'developer', 'es', 'developing-an-mvc-component', 'Desarrollo de un componente MVC'),
(349, 'developer', 'es', 'mvc-anatomy', 'Anatomía de MVC'),
(350, 'developer', 'es', 'mvc-examples', 'Ejemplos de MVC'),
(351, 'developer', 'es', 'cli-development', 'Desarrollo CLI'),
(352, 'developer', 'es', 'database', 'Base de datos'),
(353, 'developer', 'es', 'coding-examples', 'Ejemplos de codificación'),
(354, 'developer', 'es', 'advanced-developer', 'Desarrollador avanzado'),
(355, 'developer', 'es', 'advanced-administrator', 'Administrador avanzado'),
(356, 'developer', 'es', 'unclassified', 'Desclasificado'),
(357, 'help', 'nl', 'admin-modules', 'Beheermodules'),
(358, 'help', 'nl', 'articles', 'Lidwoord'),
(359, 'help', 'nl', 'banners', 'spandoeken'),
(360, 'help', 'nl', 'cache', 'Cache'),
(361, 'help', 'nl', 'chunks', 'Brokken'),
(362, 'help', 'nl', 'component', 'Onderdeel'),
(363, 'help', 'nl', 'components', 'Componenten'),
(364, 'help', 'nl', 'contacts', 'Contacten'),
(365, 'help', 'nl', 'content-security-policy', 'Neem contact op met het beveiligingsbeleid'),
(366, 'help', 'nl', 'editors', 'Editors'),
(367, 'help', 'nl', 'extensions', 'Extensies'),
(368, 'help', 'nl', 'fields', 'Velden'),
(369, 'help', 'nl', 'glossary', 'Woordenlijst'),
(370, 'help', 'nl', 'help-screens', 'Help-schermen'),
(371, 'help', 'nl', 'information', 'Informatie'),
(372, 'help', 'nl', 'install-or-update', 'Installeren of updaten'),
(373, 'help', 'nl', 'languages', 'Talen'),
(374, 'help', 'nl', 'mail', 'Mail'),
(375, 'help', 'nl', 'media', 'media'),
(376, 'help', 'nl', 'menu-items', 'menu items'),
(377, 'help', 'nl', 'menus', 'Menu\'s'),
(378, 'help', 'nl', 'messages', 'Berichten'),
(379, 'help', 'nl', 'modules', 'modules'),
(380, 'help', 'nl', 'multilingual-associations', 'Meertalige verenigingen'),
(381, 'help', 'nl', 'my-profile', 'Mijn profiel'),
(382, 'help', 'nl', 'news-feed', 'Nieuwsfeed'),
(383, 'help', 'nl', 'permissions', 'Rechten'),
(384, 'help', 'nl', 'plugins', 'Plug-ins'),
(385, 'help', 'nl', 'post-install-messages', 'Berichten na installatie'),
(386, 'help', 'nl', 'privacy', 'Privacy'),
(387, 'help', 'nl', 'private-messages', 'Prive berichten'),
(388, 'help', 'nl', 'redirect', 'Omleiden'),
(389, 'help', 'nl', 'site', 'Site'),
(390, 'help', 'nl', 'site-modules', 'Site-modules'),
(391, 'help', 'nl', 'smart-search', 'Slim zoeken'),
(392, 'help', 'nl', 'tags', 'Labels'),
(393, 'help', 'nl', 'templates', 'Sjablonen'),
(394, 'help', 'nl', 'update-sites', 'Sites bijwerken'),
(395, 'help', 'nl', 'users', 'Gebruikers'),
(396, 'help', 'nl', 'workflow', 'Werkstroom'),
(397, 'user', 'nl', 'getting-started', 'Aan de slag'),
(398, 'user', 'nl', 'articles', 'Lidwoord'),
(399, 'user', 'nl', 'articles-access', 'Artikelen - Toegang'),
(400, 'user', 'nl', 'articles-metadata', 'Artikelen - Metagegevens'),
(401, 'user', 'nl', 'banners', 'spandoeken'),
(402, 'user', 'nl', 'command-line-interface', 'Commando'),
(403, 'user', 'nl', 'configuration', 'Configuratie'),
(404, 'user', 'nl', 'contacts', 'Contacten'),
(405, 'user', 'nl', 'dashboards', 'Dashboards'),
(406, 'user', 'nl', 'editors', 'Editors'),
(407, 'user', 'nl', 'extensions', 'Extensies'),
(408, 'user', 'nl', 'fields', 'Velden'),
(409, 'user', 'nl', 'help', 'Hulp'),
(410, 'user', 'nl', 'hosting', 'Hosting'),
(411, 'user', 'nl', 'installation-variations', 'Installatie variaties'),
(412, 'user', 'nl', 'languages', 'Talen'),
(413, 'user', 'nl', 'media', 'Media'),
(414, 'user', 'nl', 'menus', 'Menu\'s'),
(415, 'user', 'nl', 'migration', 'Migratie'),
(416, 'user', 'nl', 'modules', 'modules'),
(417, 'user', 'nl', 'news-feeds', 'Nieuwsfeeds'),
(418, 'user', 'nl', 'performance', 'Prestatie'),
(419, 'user', 'nl', 'plugins', 'Plug-ins'),
(420, 'user', 'nl', 'privacy', 'Privacy'),
(421, 'user', 'nl', 'problems', 'Problemen'),
(422, 'user', 'nl', 'reference', 'Referentie'),
(423, 'user', 'nl', 'security', 'Beveiliging'),
(424, 'user', 'nl', 'seo', 'SEO'),
(425, 'user', 'nl', 'smart-search', 'Slim zoeken'),
(426, 'user', 'nl', 'system', 'Systeem'),
(427, 'user', 'nl', 'tags', 'Labels'),
(428, 'user', 'nl', 'templates', 'Sjablonen'),
(429, 'user', 'nl', 'template-tips', 'Sjabloontips'),
(430, 'user', 'nl', 'test-installations', 'Installaties testen'),
(431, 'user', 'nl', 'users', 'Gebruikers'),
(432, 'user', 'nl', 'workflows', 'Werkstromen'),
(433, 'developer', 'nl', 'getting-started', 'Aan de slag'),
(434, 'developer', 'nl', 'developer-information', 'Ontwikkelaarsinformatie'),
(435, 'developer', 'nl', 'plugin-development', 'Ontwikkeling van plug-ins'),
(436, 'developer', 'nl', 'module-development', 'Module-ontwikkeling'),
(437, 'developer', 'nl', 'developing-an-mvc-component', 'Een MVC-component ontwikkelen'),
(438, 'developer', 'nl', 'mvc-anatomy', 'MVC-anatomie'),
(439, 'developer', 'nl', 'mvc-examples', 'MVC-voorbeelden'),
(440, 'developer', 'nl', 'cli-development', 'CLI-ontwikkeling'),
(441, 'developer', 'nl', 'database', 'Databank'),
(442, 'developer', 'nl', 'coding-examples', 'Codeervoorbeelden'),
(443, 'developer', 'nl', 'advanced-developer', 'Geavanceerde ontwikkelaar'),
(444, 'developer', 'nl', 'advanced-administrator', 'Geavanceerde beheerder'),
(445, 'developer', 'nl', 'unclassified', 'Niet geclassificeerd'),
(446, 'help', 'pt', 'admin-modules', 'Módulos Administrativos'),
(447, 'help', 'pt', 'articles', 'Artigos'),
(448, 'help', 'pt', 'banners', 'Banners'),
(449, 'help', 'pt', 'cache', 'Cache'),
(450, 'help', 'pt', 'chunks', 'Pedaços'),
(451, 'help', 'pt', 'component', 'Componente'),
(452, 'help', 'pt', 'components', 'Componentes'),
(453, 'help', 'pt', 'contacts', 'Contatos'),
(454, 'help', 'pt', 'content-security-policy', 'Política de segurança de contato'),
(455, 'help', 'pt', 'editors', 'Editores'),
(456, 'help', 'pt', 'extensions', 'Extensões'),
(457, 'help', 'pt', 'fields', 'Campos'),
(458, 'help', 'pt', 'glossary', 'Glossário'),
(459, 'help', 'pt', 'help-screens', 'Telas de ajuda'),
(460, 'help', 'pt', 'information', 'Informações'),
(461, 'help', 'pt', 'install-or-update', 'Instalar ou Atualizar'),
(462, 'help', 'pt', 'languages', 'línguas'),
(463, 'help', 'pt', 'mail', 'Correspondência'),
(464, 'help', 'pt', 'media', 'meios de comunicação'),
(465, 'help', 'pt', 'menu-items', 'itens do menu'),
(466, 'help', 'pt', 'menus', 'Menus'),
(467, 'help', 'pt', 'messages', 'mensagens'),
(468, 'help', 'pt', 'modules', 'Módulos'),
(469, 'help', 'pt', 'multilingual-associations', 'Associações multilíngues'),
(470, 'help', 'pt', 'my-profile', 'Meu perfil'),
(471, 'help', 'pt', 'news-feed', 'Notícias'),
(472, 'help', 'pt', 'permissions', 'Permissões'),
(473, 'help', 'pt', 'plugins', 'Plugins'),
(474, 'help', 'pt', 'post-install-messages', 'Mensagens pós-instalação'),
(475, 'help', 'pt', 'privacy', 'Privacidade'),
(476, 'help', 'pt', 'private-messages', 'Mensagens privadas'),
(477, 'help', 'pt', 'redirect', 'redirecionar'),
(478, 'help', 'pt', 'site', 'Site'),
(479, 'help', 'pt', 'site-modules', 'Módulos do site'),
(480, 'help', 'pt', 'smart-search', 'Busca inteligente'),
(481, 'help', 'pt', 'tags', 'Tag'),
(482, 'help', 'pt', 'templates', 'Modelos'),
(483, 'help', 'pt', 'update-sites', 'Sites de atualização'),
(484, 'help', 'pt', 'users', 'Usuários'),
(485, 'help', 'pt', 'workflow', 'fluxo de trabalho'),
(486, 'user', 'pt', 'getting-started', 'Começando'),
(487, 'user', 'pt', 'articles', 'Artigos'),
(488, 'user', 'pt', 'articles-access', 'Artigos - Acesso'),
(489, 'user', 'pt', 'articles-metadata', 'Artigos - Metadados'),
(490, 'user', 'pt', 'banners', 'Banners'),
(491, 'user', 'pt', 'command-line-interface', 'Comando'),
(492, 'user', 'pt', 'configuration', 'Configuração'),
(493, 'user', 'pt', 'contacts', 'Contatos'),
(494, 'user', 'pt', 'dashboards', 'Painéis'),
(495, 'user', 'pt', 'editors', 'Editores'),
(496, 'user', 'pt', 'extensions', 'Extensões'),
(497, 'user', 'pt', 'fields', 'Campos'),
(498, 'user', 'pt', 'help', 'Ajuda'),
(499, 'user', 'pt', 'hosting', 'Hospedagem'),
(500, 'user', 'pt', 'installation-variations', 'Variações de instalação'),
(501, 'user', 'pt', 'languages', 'línguas'),
(502, 'user', 'pt', 'media', 'meios de comunicação'),
(503, 'user', 'pt', 'menus', 'Menus'),
(504, 'user', 'pt', 'migration', 'Migração'),
(505, 'user', 'pt', 'modules', 'Módulos'),
(506, 'user', 'pt', 'news-feeds', 'Feed de notícias'),
(507, 'user', 'pt', 'performance', 'Desempenho'),
(508, 'user', 'pt', 'plugins', 'Plugins'),
(509, 'user', 'pt', 'privacy', 'Privacidade'),
(510, 'user', 'pt', 'problems', 'problemas'),
(511, 'user', 'pt', 'reference', 'Referência'),
(512, 'user', 'pt', 'security', 'Segurança'),
(513, 'user', 'pt', 'seo', 'SEO'),
(514, 'user', 'pt', 'smart-search', 'Busca inteligente'),
(515, 'user', 'pt', 'system', 'Sistema'),
(516, 'user', 'pt', 'tags', 'Tag'),
(517, 'user', 'pt', 'templates', 'Modelos'),
(518, 'user', 'pt', 'template-tips', 'Dicas de modelo'),
(519, 'user', 'pt', 'test-installations', 'Instalações de teste'),
(520, 'user', 'pt', 'users', 'Usuários'),
(521, 'user', 'pt', 'workflows', 'fluxos de trabalho'),
(522, 'developer', 'pt', 'getting-started', 'Começando'),
(523, 'developer', 'pt', 'developer-information', 'Informações do desenvolvedor'),
(524, 'developer', 'pt', 'plugin-development', 'Desenvolvimento de plug-ins'),
(525, 'developer', 'pt', 'module-development', 'Desenvolvimento de módulo'),
(526, 'developer', 'pt', 'developing-an-mvc-component', 'Desenvolvendo um componente MVC'),
(527, 'developer', 'pt', 'mvc-anatomy', 'Anatomia MVC'),
(528, 'developer', 'pt', 'mvc-examples', 'Exemplos de MVC'),
(529, 'developer', 'pt', 'cli-development', 'Desenvolvimento CLI'),
(530, 'developer', 'pt', 'database', 'Base de dados'),
(531, 'developer', 'pt', 'coding-examples', 'Exemplos de Codificação'),
(532, 'developer', 'pt', 'advanced-developer', 'Desenvolvedor Avançado'),
(533, 'developer', 'pt', 'advanced-administrator', 'Administrador Avançado'),
(534, 'developer', 'pt', 'unclassified', 'Não classificado'),
(535, 'help', 'pt-br', 'admin-modules', 'Módulos Administrativos'),
(536, 'help', 'pt-br', 'articles', 'Artigos'),
(537, 'help', 'pt-br', 'banners', 'Banners'),
(538, 'help', 'pt-br', 'cache', 'Cache'),
(539, 'help', 'pt-br', 'chunks', 'Pedaços'),
(540, 'help', 'pt-br', 'component', 'Componente'),
(541, 'help', 'pt-br', 'components', 'Componentes'),
(542, 'help', 'pt-br', 'contacts', 'Contatos'),
(543, 'help', 'pt-br', 'content-security-policy', 'Política de segurança de contato'),
(544, 'help', 'pt-br', 'editors', 'Editores'),
(545, 'help', 'pt-br', 'extensions', 'Extensões'),
(546, 'help', 'pt-br', 'fields', 'Campos'),
(547, 'help', 'pt-br', 'glossary', 'Glossário'),
(548, 'help', 'pt-br', 'help-screens', 'Telas de ajuda'),
(549, 'help', 'pt-br', 'information', 'Informações'),
(550, 'help', 'pt-br', 'install-or-update', 'Instalar ou Atualizar'),
(551, 'help', 'pt-br', 'languages', 'línguas'),
(552, 'help', 'pt-br', 'mail', 'Correspondência'),
(553, 'help', 'pt-br', 'media', 'meios de comunicação'),
(554, 'help', 'pt-br', 'menu-items', 'itens do menu'),
(555, 'help', 'pt-br', 'menus', 'Menus'),
(556, 'help', 'pt-br', 'messages', 'mensagens'),
(557, 'help', 'pt-br', 'modules', 'Módulos'),
(558, 'help', 'pt-br', 'multilingual-associations', 'Associações multilíngues'),
(559, 'help', 'pt-br', 'my-profile', 'Meu perfil'),
(560, 'help', 'pt-br', 'news-feed', 'Notícias'),
(561, 'help', 'pt-br', 'permissions', 'Permissões'),
(562, 'help', 'pt-br', 'plugins', 'Plugins'),
(563, 'help', 'pt-br', 'post-install-messages', 'Mensagens pós-instalação'),
(564, 'help', 'pt-br', 'privacy', 'Privacidade'),
(565, 'help', 'pt-br', 'private-messages', 'Mensagens privadas'),
(566, 'help', 'pt-br', 'redirect', 'redirecionar'),
(567, 'help', 'pt-br', 'site', 'Site'),
(568, 'help', 'pt-br', 'site-modules', 'Módulos do site'),
(569, 'help', 'pt-br', 'smart-search', 'Busca inteligente'),
(570, 'help', 'pt-br', 'tags', 'Tag'),
(571, 'help', 'pt-br', 'templates', 'Modelos'),
(572, 'help', 'pt-br', 'update-sites', 'Sites de atualização'),
(573, 'help', 'pt-br', 'users', 'Usuários'),
(574, 'help', 'pt-br', 'workflow', 'fluxo de trabalho'),
(575, 'user', 'pt-br', 'getting-started', 'Começando'),
(576, 'user', 'pt-br', 'articles', 'Artigos'),
(577, 'user', 'pt-br', 'articles-access', 'Artigos - Acesso'),
(578, 'user', 'pt-br', 'articles-metadata', 'Artigos - Metadados'),
(579, 'user', 'pt-br', 'banners', 'Banners'),
(580, 'user', 'pt-br', 'command-line-interface', 'Comando'),
(581, 'user', 'pt-br', 'configuration', 'Configuração'),
(582, 'user', 'pt-br', 'contacts', 'Contatos'),
(583, 'user', 'pt-br', 'dashboards', 'Painéis'),
(584, 'user', 'pt-br', 'editors', 'Editores'),
(585, 'user', 'pt-br', 'extensions', 'Extensões'),
(586, 'user', 'pt-br', 'fields', 'Campos'),
(587, 'user', 'pt-br', 'help', 'Ajuda'),
(588, 'user', 'pt-br', 'hosting', 'Hospedagem'),
(589, 'user', 'pt-br', 'installation-variations', 'Variações de instalação'),
(590, 'user', 'pt-br', 'languages', 'línguas'),
(591, 'user', 'pt-br', 'media', 'meios de comunicação'),
(592, 'user', 'pt-br', 'menus', 'Menus'),
(593, 'user', 'pt-br', 'migration', 'Migração'),
(594, 'user', 'pt-br', 'modules', 'Módulos'),
(595, 'user', 'pt-br', 'news-feeds', 'Feed de notícias'),
(596, 'user', 'pt-br', 'performance', 'Desempenho'),
(597, 'user', 'pt-br', 'plugins', 'Plugins'),
(598, 'user', 'pt-br', 'privacy', 'Privacidade'),
(599, 'user', 'pt-br', 'problems', 'problemas'),
(600, 'user', 'pt-br', 'reference', 'Referência'),
(601, 'user', 'pt-br', 'security', 'Segurança'),
(602, 'user', 'pt-br', 'seo', 'SEO'),
(603, 'user', 'pt-br', 'smart-search', 'Busca inteligente'),
(604, 'user', 'pt-br', 'system', 'Sistema'),
(605, 'user', 'pt-br', 'tags', 'Tag'),
(606, 'user', 'pt-br', 'templates', 'Modelos'),
(607, 'user', 'pt-br', 'template-tips', 'Dicas de modelo'),
(608, 'user', 'pt-br', 'test-installations', 'Instalações de teste'),
(609, 'user', 'pt-br', 'users', 'Usuários'),
(610, 'user', 'pt-br', 'workflows', 'fluxos de trabalho'),
(611, 'developer', 'pt-br', 'getting-started', 'Começando'),
(612, 'developer', 'pt-br', 'developer-information', 'Informações do desenvolvedor'),
(613, 'developer', 'pt-br', 'plugin-development', 'Desenvolvimento de plug-ins'),
(614, 'developer', 'pt-br', 'module-development', 'Desenvolvimento de módulo'),
(615, 'developer', 'pt-br', 'developing-an-mvc-component', 'Desenvolvendo um componente MVC'),
(616, 'developer', 'pt-br', 'mvc-anatomy', 'Anatomia MVC'),
(617, 'developer', 'pt-br', 'mvc-examples', 'Exemplos de MVC'),
(618, 'developer', 'pt-br', 'cli-development', 'Desenvolvimento CLI'),
(619, 'developer', 'pt-br', 'database', 'Base de dados'),
(620, 'developer', 'pt-br', 'coding-examples', 'Exemplos de Codificação'),
(621, 'developer', 'pt-br', 'advanced-developer', 'Desenvolvedor Avançado'),
(622, 'developer', 'pt-br', 'advanced-administrator', 'Administrador Avançado'),
(623, 'developer', 'pt-br', 'unclassified', 'Não classificado'),
(624, 'help', 'ru', 'admin-modules', 'Административные модули'),
(625, 'help', 'ru', 'articles', 'Статьи'),
(626, 'help', 'ru', 'banners', 'Баннеры'),
(627, 'help', 'ru', 'cache', 'Кэш'),
(628, 'help', 'ru', 'chunks', 'Куски'),
(629, 'help', 'ru', 'component', 'Компонент'),
(630, 'help', 'ru', 'components', 'Компоненты'),
(631, 'help', 'ru', 'contacts', 'Контакты'),
(632, 'help', 'ru', 'content-security-policy', 'Политика безопасности контакта'),
(633, 'help', 'ru', 'editors', 'Редакторы'),
(634, 'help', 'ru', 'extensions', 'Расширения'),
(635, 'help', 'ru', 'fields', 'Поля'),
(636, 'help', 'ru', 'glossary', 'Глоссарий'),
(637, 'help', 'ru', 'help-screens', 'Экраны справки'),
(638, 'help', 'ru', 'information', 'Информация'),
(639, 'help', 'ru', 'install-or-update', 'Установить или обновить'),
(640, 'help', 'ru', 'languages', 'Языки'),
(641, 'help', 'ru', 'mail', 'Почта'),
(642, 'help', 'ru', 'media', 'СМИ'),
(643, 'help', 'ru', 'menu-items', 'Пункты меню'),
(644, 'help', 'ru', 'menus', 'Меню'),
(645, 'help', 'ru', 'messages', 'Сообщения'),
(646, 'help', 'ru', 'modules', 'Модули'),
(647, 'help', 'ru', 'multilingual-associations', 'Многоязычные ассоциации'),
(648, 'help', 'ru', 'my-profile', 'Мой профайл'),
(649, 'help', 'ru', 'news-feed', 'Новостная лента'),
(650, 'help', 'ru', 'permissions', 'Разрешения'),
(651, 'help', 'ru', 'plugins', 'Плагины'),
(652, 'help', 'ru', 'post-install-messages', 'Сообщения после установки'),
(653, 'help', 'ru', 'privacy', 'Конфиденциальность'),
(654, 'help', 'ru', 'private-messages', 'Приватные сообщения'),
(655, 'help', 'ru', 'redirect', 'перенаправить'),
(656, 'help', 'ru', 'site', 'Сайт'),
(657, 'help', 'ru', 'site-modules', 'Модули сайта'),
(658, 'help', 'ru', 'smart-search', 'Умный поиск'),
(659, 'help', 'ru', 'tags', 'Теги'),
(660, 'help', 'ru', 'templates', 'Шаблоны'),
(661, 'help', 'ru', 'update-sites', 'Обновление сайтов'),
(662, 'help', 'ru', 'users', 'Пользователи'),
(663, 'help', 'ru', 'workflow', 'Рабочий процесс'),
(664, 'user', 'ru', 'getting-started', 'Начиная'),
(665, 'user', 'ru', 'articles', 'Статьи'),
(666, 'user', 'ru', 'articles-access', 'Статьи - Доступ'),
(667, 'user', 'ru', 'articles-metadata', 'Статьи - Метаданные'),
(668, 'user', 'ru', 'banners', 'Баннеры'),
(669, 'user', 'ru', 'command-line-interface', 'Команда'),
(670, 'user', 'ru', 'configuration', 'Конфигурация'),
(671, 'user', 'ru', 'contacts', 'Контакты'),
(672, 'user', 'ru', 'dashboards', 'Панели мониторинга'),
(673, 'user', 'ru', 'editors', 'Редакторы'),
(674, 'user', 'ru', 'extensions', 'Расширения'),
(675, 'user', 'ru', 'fields', 'Поля'),
(676, 'user', 'ru', 'help', 'Помощь'),
(677, 'user', 'ru', 'hosting', 'Хостинг'),
(678, 'user', 'ru', 'installation-variations', 'Варианты установки'),
(679, 'user', 'ru', 'languages', 'Языки'),
(680, 'user', 'ru', 'media', 'СМИ'),
(681, 'user', 'ru', 'menus', 'Меню'),
(682, 'user', 'ru', 'migration', 'Миграция'),
(683, 'user', 'ru', 'modules', 'Модули'),
(684, 'user', 'ru', 'news-feeds', 'Ленты новостей'),
(685, 'user', 'ru', 'performance', 'Производительность'),
(686, 'user', 'ru', 'plugins', 'Плагины'),
(687, 'user', 'ru', 'privacy', 'Конфиденциальность'),
(688, 'user', 'ru', 'problems', 'Проблемы'),
(689, 'user', 'ru', 'reference', 'Ссылка'),
(690, 'user', 'ru', 'security', 'Безопасность'),
(691, 'user', 'ru', 'seo', 'SEO'),
(692, 'user', 'ru', 'smart-search', 'Умный поиск'),
(693, 'user', 'ru', 'system', 'Система'),
(694, 'user', 'ru', 'tags', 'Теги'),
(695, 'user', 'ru', 'templates', 'Шаблоны'),
(696, 'user', 'ru', 'template-tips', 'Советы по шаблонам'),
(697, 'user', 'ru', 'test-installations', 'Тестовые установки'),
(698, 'user', 'ru', 'users', 'Пользователи'),
(699, 'user', 'ru', 'workflows', 'Рабочие процессы'),
(700, 'developer', 'ru', 'getting-started', 'Начиная'),
(701, 'developer', 'ru', 'developer-information', 'Информация для разработчиков'),
(702, 'developer', 'ru', 'plugin-development', 'Разработка плагинов'),
(703, 'developer', 'ru', 'module-development', 'Разработка модуля'),
(704, 'developer', 'ru', 'developing-an-mvc-component', 'Разработка компонента MVC'),
(705, 'developer', 'ru', 'mvc-anatomy', 'Анатомия MVC'),
(706, 'developer', 'ru', 'mvc-examples', 'Примеры MVC'),
(707, 'developer', 'ru', 'cli-development', 'Разработка интерфейса командной строки'),
(708, 'developer', 'ru', 'database', 'База данных'),
(709, 'developer', 'ru', 'coding-examples', 'Примеры кодирования'),
(710, 'developer', 'ru', 'advanced-developer', 'Продвинутый разработчик'),
(711, 'developer', 'ru', 'advanced-administrator', 'Расширенный администратор'),
(712, 'developer', 'ru', 'unclassified', 'Неклассифицированный'),
(713, 'help', 'en', 'guided-tours', 'Guided Tours'),
(714, 'help', 'de', 'guided-tours', 'Führungen'),
(715, 'help', 'es', 'guided-tours', 'Visitas guiadas'),
(716, 'help', 'fr', 'guided-tours', 'Visites guidées'),
(717, 'help', 'nl', 'guided-tours', 'Rondleidingen met gids'),
(718, 'help', 'pt', 'guided-tours', 'Visitas guiadas'),
(719, 'help', 'pt-br', 'guided-tours', 'Visitas guiadas'),
(720, 'help', 'ru', 'guided-tours', 'Экскурсии'),
(713, 'help', 'en', 'news', 'News'),
(714, 'help', 'de', 'news', 'Nachricht'),
(715, 'help', 'es', 'news', 'Noticias'),
(716, 'help', 'fr', 'news', 'Nouvelles'),
(717, 'help', 'nl', 'news', 'Nieuws'),
(718, 'help', 'pt', 'news', 'Notícias'),
(719, 'help', 'pt-br', 'news', 'Notícias'),
(720, 'help', 'ru', 'news', 'Новости');

